language: go
go_import_path: github.com/darcys22/godbledger
sudo: false
jobs:

  include:

    # These are the latest Go versions.
    - stage: build
      os: linux
      arch: amd64
      dist: bionic
      go: 1.13.x
      env:
        - GO111MODULE=on
      script:
        - go run utils/ci.go install
        - go run utils/ci.go test -coverage $TEST_PACKAGES




