name: releases
on:
  push:
    tags:
      - 'v*'
jobs:
  ubuntu:
    strategy:
      fail-fast: true
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    environment: "PPA Signing Environment"
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install debscripts
      run: sudo apt-get install devscripts
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Push PPA
      shell: 'script -q -e -c "bash {0}"'
      env: 
        PPA_SIGNING_KEY: ${{ secrets.PPA_SIGNING_KEY }}
        PPA_SSH_KEY: ${{ secrets.PPA_SSH_KEY }}
      run: |
        mkdir -p /home/runner/.ssh
        mkdir -p /home/runner/.gnupg
        echo 'use-agent' >> ~/.gnupg/gpg.conf
        echo 'pinentry-mode loopback' >> ~/.gnupg/gpg.conf
        echo 'allow-loopback-pinentry' >> ~/.gnupg/gpg-agent.conf
        echo 'RELOADAGENT' | gpg-connect-agent
        echo '|1|7SiYPr9xl3uctzovOTj4gMwAC1M=|t6ReES75Bo/PxlOPJ6/GsGbTrM0= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA0aKz5UTUndYgIGG7dQBV+HaeuEZJ2xPHo2DS2iSKvUL4xNMSAY4UguNW+pX56nAQmZKIZZ8MaEvSj6zMEDiq6HFfn5JcTlM80UwlnyKe8B8p7Nk06PPQLrnmQt5fh0HmEcZx+JU9TZsfCHPnX7MNz4ELfZE6cFsclClrKim3BHUIGq//t93DllB+h4O9LHjEUsQ1Sr63irDLSutkLJD6RXchjROXkNirlcNVHH/jwLWR5RcYilNX7S5bIkK8NlWPjsn/8Ua5O7I9/YoE97PpO6i73DTGLh5H9JN/SITwCKBkgSDWUt61uPK3Y11Gty7o2lWsBjhBUm2Y38CBsoGmBw==' >> ~/.ssh/known_hosts
        go run utils/ci.go debsrc -upload darcys22/godbledger -sftp-user darcys22 -signer "Sean Darcy <sean@darcyfinancial.com>" 
  github:
    strategy:
      fail-fast: true
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    environment: "PPA Signing Environment"
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        path: go/src/github.com/darcys22/godbledger
    - name: Push Github Release
      env: 
        GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        GOPATH: /home/runner/work/godbledger/godbledger/go
      run: |
        cd go/src/github.com/darcys22/godbledger
        make github
